#define KARMA_CATEGORY_SURVIVAL "karma_survival"
#define KARMA_CATEGORY_EXPRESSION "karma_expression"
#define KARMA_CATEGORY_SOCIALIZATION "karma_socialization"
#define KARMA_CATEGORY_SPIRITUAL "karma_spiritual"

#define KARMA_LEVEL_ONE 1
#define KARMA_LEVEL_TWO 2
#define KARMA_LEVEL_THREE 4

#define BEAUTY_LEVEL_HORRID -66
#define BEAUTY_LEVEL_BAD -33
#define BEAUTY_LEVEL_DECENT 33
#define BEAUTY_LEVEL_GOOD 66
#define BEAUTY_LEVEL_GREAT 100

#define KARMA_LEVEL_HAPPY4 15
#define KARMA_LEVEL_HAPPY3 10
#define KARMA_LEVEL_HAPPY2 6
#define KARMA_LEVEL_HAPPY1 2
#define KARMA_LEVEL_NEUTRAL 0
#define KARMA_LEVEL_SAD1 -3
#define KARMA_LEVEL_SAD2 -7
#define KARMA_LEVEL_SAD3 -15
#define KARMA_LEVEL_SAD4 -20

#define SPIRIT_MAXIMUM 150
#define SPIRIT_HIGH 125
#define SPIRIT_NEUTRAL 100
#define SPIRIT_DISTURBED 75
#define SPIRIT_POOR 50
#define SPIRIT_LOW 25
#define SPIRIT_BAD 0
